FROM busybox:1.25
MAINTAINER https://github.com/cloudfoundry/garden-dockerfiles
ENV PATH /usr/local/bin:/usr/bin:/bin:/from-dockerfile
ENV TEST test-from-dockerfile
ENV TEST second-test-from-dockerfile:$TEST
