- hosts: all
  become: true
  become_method: sudo
  tags: [vm, docker]
  tasks:
  - command: "{{item}}"
    with_items:
    - "{{garden_ci_ubuntu}}/scripts/passwordless_sudo.sh"
    - "{{garden_ci_ubuntu}}/scripts/provision.sh"
    - "{{garden_ci_ubuntu}}/scripts/build_static_assets.sh"
    - "{{garden_ci_ubuntu}}/scripts/build_apparmor.sh"
    - "{{garden_ci_ubuntu}}/scripts/cleanup.sh"

  - file: path=/opt/warden state=directory mode=0755

  - copy:
      src: "{{garden_ci_ubuntu}}/dependencies/{{item.tarname}}.tar"
      dest: "/opt/warden/{{item.dest}}.tar"
      remote_src: true
    with_items:
    - {tarname: busybox, dest: rootfs}
    - {tarname: ubuntu, dest: nestable-rootfs}
    - {tarname: docker_registry, dest: docker-registry-rootfs}
    - {tarname: docker_registry_v2, dest: docker-registry-v2-rootfs}
    - {tarname: preexisting_users, dest: preexisting-users-rootfs}
    - {tarname: fuse, dest: fuse-rootfs}

- hosts: all
  become: true
  become_method: sudo
  tags: [vm]
  tasks:
  - apt:
      name: linux-generic-lts-xenial
      update_cache: true
      install_recommends: true

  - lineinfile: path=/etc/modules line=overlay

  - lineinfile:
      path: "/etc/sub{{item}}id"
      regexp: "rootless:.*"
      line: "rootless:100000:65536"
    with_items: [u, g]

  - lineinfile:
      path: /etc/default/grub
      regexp: "GRUB_CMDLINE_LINUX=.*"
      line: 'GRUB_CMDLINE_LINUX="swapaccount=1"'

  - command: /usr/sbin/update-grub
